apiVersion: apps/v1
kind: Deployment
metadata:
  name: webchat_react_deployment
  labels:
    app: webchat_react
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webchat_react
  template:
    metadata:
      labels:
        app: webchat_react
    spec:
      containers:
      - name: webchat_react
        image: webchat_react:latest
        ports:
        - containerPort: 80